## Load title.akas.tsv

In [1]:
import pandas as pd
import numpy as np

In [2]:
akas_df = pd.read_csv("https://datasets.imdbws.com/title.akas.tsv.gz", sep="\t", dtype={'isOriginalTitle': str})

In [3]:
akas_df.head(10)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,\N,imdbDisplay,\N,0
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
3,tt0000001,4,Καρμενσίτα,GR,\N,imdbDisplay,\N,0
4,tt0000001,5,Карменсита,RU,\N,imdbDisplay,\N,0
5,tt0000001,6,Carmencita,US,\N,imdbDisplay,\N,0
6,tt0000001,7,Carmencita,\N,\N,original,\N,1
7,tt0000001,8,カルメンチータ,JP,ja,imdbDisplay,\N,0
8,tt0000002,1,Le clown et ses chiens,\N,\N,original,\N,1
9,tt0000002,2,Le clown et ses chiens,FR,\N,imdbDisplay,\N,0

In [4]:
akas_df.tail(10)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
29617568,tt9916850,7,Folge #3.19,DE,de,\N,\N,0
29617569,tt9916852,1,Episodio #3.20,ES,es,\N,\N,0
29617570,tt9916852,2,Épisode #3.20,FR,fr,\N,\N,0
29617571,tt9916852,3,Folge #3.20,DE,de,\N,\N,0
29617572,tt9916852,4,エピソード #3.20,JP,ja,\N,\N,0
29617573,tt9916852,5,Episódio #3.20,PT,pt,\N,\N,0
29617574,tt9916852,6,Episodio #3.20,IT,it,\N,\N,0
29617575,tt9916852,7,एपिसोड #3.20,IN,hi,\N,\N,0
29617576,tt9916856,1,The Wind,DE,\N,imdbDisplay,\N,0
29617577,tt9916856,2,The Wind,\N,\N,original,\N,1

In [5]:
akas_df.replace('\\N', np.nan)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,NaN,imdbDisplay,NaN,0
1,tt0000001,2,Carmencita,DE,NaN,NaN,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,NaN,imdbDisplay,NaN,0
3,tt0000001,4,Καρμενσίτα,GR,NaN,imdbDisplay,NaN,0
4,tt0000001,5,Карменсита,RU,NaN,imdbDisplay,NaN,0
5,tt0000001,6,Carmencita,US,NaN,imdbDisplay,NaN,0
6,tt0000001,7,Carmencita,NaN,NaN,original,NaN,1
7,tt0000001,8,カルメンチータ,JP,ja,imdbDisplay,NaN,0
8,tt0000002,1,Le clown et ses chiens,NaN,NaN,original,NaN,1
9,tt0000002,2,Le clown et ses chiens,FR,NaN,imdbDisplay,NaN,0
10,tt0000002,3,A bohóc és kutyái,HU,NaN,imdbDisplay,NaN,0
11,tt0000002,4,Der Clown und seine Hunde,DE,NaN,NaN,literal title,0
12,tt0000002,5,Clovnul si cainii sai,RO,NaN,imdbDisplay,NaN,0
13,tt0000002,6,Клоун и его собаки,RU,NaN,imdbDisplay,NaN,0
14,tt0000002,7,The Clown and His Dogs,US,NaN,NaN,literal English title,0
15,tt0000002,8,道化師と犬,JP,ja,imdbDisplay,NaN,0
16,tt0000003,1,Sarmanul Pierrot,RO,NaN,imdbDisplay,NaN,0
17,tt0000003,2,Szegény Pierrot,HU,NaN,imdbDisplay,NaN,0
18,tt0000003,3,哀れなピエロ,JP,ja,imdbDisplay,NaN,0
19,tt0000003,4,Бідний П'єро,UA,NaN,imdbDisplay,NaN,0
20,tt0000003,5,Бедный Пьеро,RU,NaN,imdbDisplay,NaN,0
21,tt0000003,6,Pauvre Pierrot,NaN,NaN,original,NaN,1
22,tt0000003,7,Poor Pierrot,GB,NaN,imdbDisplay,NaN,0
23,tt0000003,8,Pauvre Pierrot,FR,NaN,imdbDisplay,NaN,0
24,tt0000003,9,Armer Pierrot,DE,NaN,NaN,literal title,0
25,tt0000004,1,Un bon bock,NaN,NaN,original,NaN,1
26,tt0000004,2,Un bon bock,FR,NaN,imdbDisplay,NaN,0
27,tt0000004,3,Ein gutes Glas Bier,DE,NaN,NaN,literal title,0
28,tt0000004,4,Un ţap de bere,RO,NaN,imdbDisplay,NaN,0
29,tt0000004,5,Полная кружка пива,RU,NaN,imdbDisplay,NaN,0
...,...,...,...,...,...,...,...,...
29617548,tt9916846,1,Épisode #3.18,FR,fr,NaN,NaN,0
29617549,tt9916846,2,Folge #3.18,DE,de,NaN,NaN,0
29617550,tt9916846,3,エピソード #3.18,JP,ja,NaN,NaN,0
29617551,tt9916846,4,Episódio #3.18,PT,pt,NaN,NaN,0
29617552,tt9916846,5,एपिसोड #3.18,IN,hi,NaN,NaN,0
29617553,tt9916846,6,Episodio #3.18,IT,it,NaN,NaN,0
29617554,tt9916846,7,Episodio #3.18,ES,es,NaN,NaN,0
29617555,tt9916848,1,Épisode #3.17,FR,fr,NaN,NaN,0
29617556,tt9916848,2,Folge #3.17,DE,de,NaN,NaN,0
29617557,tt9916848,3,エピソード #3.17,JP,ja,NaN,NaN,0
29617558,tt9916848,4,Episódio #3.17,PT,pt,NaN,NaN,0
29617559,tt9916848,5,Episodio #3.17,IT,it,NaN,NaN,0
29617560,tt9916848,6,एपिसोड #3.17,IN,hi,NaN,NaN,0
29617561,tt9916848,7,Episodio #3.17,ES,es,NaN,NaN,0
29617562,tt9916850,1,Episódio #3.19,PT,pt,NaN,NaN,0
29617563,tt9916850,2,एपिसोड #3.19,IN,hi,NaN,NaN,0
29617564,tt9916850,3,Épisode #3.19,FR,fr,NaN,NaN,0
29617565,tt9916850,4,エピソード #3.19,JP,ja,NaN,NaN,0
29617566,tt9916850,5,Episodio #3.19,IT,it,NaN,NaN,0
29617567,tt9916850,6,Episodio #3.19,ES,es,NaN,NaN,0
29617568,tt9916850,7,Folge #3.19,DE,de,NaN,NaN,0
29617569,tt9916852,1,Episodio #3.20,ES,es,NaN,NaN,0
29617570,tt9916852,2,Épisode #3.20,FR,fr,NaN,NaN,0
29617571,tt9916852,3,Folge #3.20,DE,de,NaN,NaN,0
29617572,tt9916852,4,エピソード #3.20,JP,ja,NaN,NaN,0
29617573,tt9916852,5,Episódio #3.20,PT,pt,NaN,NaN,0
29617574,tt9916852,6,Episodio #3.20,IT,it,NaN,NaN,0
29617575,tt9916852,7,एपिसोड #3.20,IN,hi,NaN,NaN,0
29617576,tt9916856,1,The Wind,DE,NaN,imdbDisplay,NaN,0
29617577,tt9916856,2,The Wind,NaN,NaN,original,NaN,1

In [7]:
akas_df[akas_df.titleId == 'tt9914928']

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
29614509,tt9914928,1,Noblesse Oblige,\N,\N,original,\N,1
29614510,tt9914928,2,Noblesse Oblige,GB,\N,imdbDisplay,\N,0

In [8]:
akas_df[akas_df.titleId == 'tt9916852']

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
29617569,tt9916852,1,Episodio #3.20,ES,es,\N,\N,0
29617570,tt9916852,2,Épisode #3.20,FR,fr,\N,\N,0
29617571,tt9916852,3,Folge #3.20,DE,de,\N,\N,0
29617572,tt9916852,4,エピソード #3.20,JP,ja,\N,\N,0
29617573,tt9916852,5,Episódio #3.20,PT,pt,\N,\N,0
29617574,tt9916852,6,Episodio #3.20,IT,it,\N,\N,0
29617575,tt9916852,7,एपिसोड #3.20,IN,hi,\N,\N,0